 export const  gkQuestions = [
  { q: "Rutherford scattering experiment se atom ke kis part ka pata chala?", options: ["Nucleus", "Electron shell", "Neutron cloud", "Valence band"], ans: "Nucleus" },
  { q: "Planck constant ki SI unit kya hoti hai?", options: ["J·s", "N·m", "W·s", "C·V"], ans: "J·s" },
  { q: "p-n junction diode ka principal effect kya hai?", options: ["Rectification", "Amplification", "Induction", "Capacitance increase"], ans: "Rectification" },
  { q: "DNA ke sugar ka naam?", options: ["Ribose", "Deoxyribose", "Glucose", "Fructose"], ans: "Deoxyribose" },
  { q: "Mitochondria ko 'powerhouse' kyon kehte hain?", options: ["ATP synthesis", "Protein digestion", "DNA replication", "Cell wall formation"], ans: "ATP synthesis" },

  { q: "Wavelength aur frequency ka relation kya hai (wave speed v constant)?", options: ["v = fλ", "v = f/λ", "v = λ/f", "v = f + λ"], ans: "v = fλ" },
  { q: "SI unit of electric current?", options: ["Ampere", "Volt", "Ohm", "Watt"], ans: "Ampere" },
  { q: "Ohm’s law ka correct form?", options: ["V = IR", "P = IV", "R = VI", "I = VR"], ans: "V = IR" },
  { q: "Faraday’s law kis cheez se related hai?", options: ["Electromagnetic induction", "Thermal expansion", "Refraction", "Nuclear fission"], ans: "Electromagnetic induction" },
  { q: "Coulomb’s law kis force ko describe karta hai?", options: ["Electrostatic", "Gravitational", "Frictional", "Buoyant"], ans: "Electrostatic" },

  { q: "SI unit of pressure?", options: ["Pascal", "Joule", "Newton", "Watt"], ans: "Pascal" },
  { q: "Work done ka SI unit?", options: ["Joule", "Watt", "Newton", "Pascal"], ans: "Joule" },
  { q: "Power ka SI unit?", options: ["Watt", "Joule", "Ampere", "Tesla"], ans: "Watt" },
  { q: "Resistivity ki SI unit?", options: ["Ω·m", "Ω/m", "m/Ω", "S·m"], ans: "Ω·m" },
  { q: "Newton ka third law kis baat ko state karta hai?", options: ["Action-Reaction equal & opposite", "F = ma", "Energy conserved", "Entropy increases"], ans: "Action-Reaction equal & opposite" },

  { q: "Glycolysis cell ke kis part me hota hai?", options: ["Cytoplasm", "Nucleus", "Mitochondria matrix", "Chloroplast stroma"], ans: "Cytoplasm" },
  { q: "Photosynthesis me oxygen kis process se aata hai?", options: ["Photolysis of water", "CO2 breakdown", "Chlorophyll oxidation", "ATP hydrolysis"], ans: "Photolysis of water" },
  { q: "Human blood ka normal pH range approx?", options: ["7.35–7.45", "6.8–7.0", "7.8–8.2", "5.5–6.0"], ans: "7.35–7.45" },
  { q: "Enzyme ka primary nature kya hota hai?", options: ["Protein", "Carbohydrate", "Lipid", "DNA"], ans: "Protein" },
  { q: "RBC ka main function?", options: ["Oxygen transport", "Antibody production", "Clotting", "Hormone synthesis"], ans: "Oxygen transport" },

  { q: "Avogadro number ka approx value?", options: ["6.022×10^23", "3.14×10^8", "9.8×10^2", "1.6×10^-19"], ans: "6.022×10^23" },
  { q: "pH 7 se kam solution ko kya kehte hain?", options: ["Acidic", "Basic", "Neutral", "Amphoteric"], ans: "Acidic" },
  { q: "Oxidation ka simplest meaning?", options: ["Loss of electrons", "Gain of electrons", "Gain of protons", "Loss of neutrons"], ans: "Loss of electrons" },
  { q: "Reduction ka simplest meaning?", options: ["Gain of electrons", "Loss of electrons", "Gain of oxygen", "Loss of hydrogen"], ans: "Gain of electrons" },
  { q: "Periodic table me group 18 elements ko kya kehte hain?", options: ["Noble gases", "Halogens", "Alkali metals", "Transition metals"], ans: "Noble gases" },

  { q: "Indian Constitution me Fundamental Duties kahan se li gayi?", options: ["USSR (Russia) model", "USA model", "UK model", "France model"], ans: "USSR (Russia) model" },
  { q: "Directive Principles ka inspiration kahan se?", options: ["Ireland", "USA", "Canada", "Japan"], ans: "Ireland" },
  { q: "Lok Sabha ka maximum term?", options: ["5 years", "6 years", "4 years", "7 years"], ans: "5 years" },
  { q: "Rajya Sabha ka member term?", options: ["6 years", "5 years", "4 years", "2 years"], ans: "6 years" },
  { q: "Money Bill sirf kahan introduce ho sakta hai?", options: ["Lok Sabha", "Rajya Sabha", "Both houses", "President office"], ans: "Lok Sabha" },

  { q: "Green Revolution ka major crop India me?", options: ["Wheat", "Tea", "Jute", "Cotton"], ans: "Wheat" },
  { q: "Reserve Bank of India ka main function?", options: ["Monetary policy & currency issue", "Law making", "Defence", "Election conduct"], ans: "Monetary policy & currency issue" },
  { q: "GDP ka full form?", options: ["Gross Domestic Product", "General Domestic Price", "Gross Development Process", "Global Domestic Product"], ans: "Gross Domestic Product" },
  { q: "Inflation ka matlab?", options: ["General price level rise", "General price level fall", "Currency ban", "Tax reduction"], ans: "General price level rise" },
  { q: "Fiscal policy primarily kis se related hai?", options: ["Government spending & taxation", "Central bank repo rate", "Rainfall pattern", "Trade winds"], ans: "Government spending & taxation" },

  { q: "UN ka headquarter kahan hai?", options: ["New York", "Geneva", "Paris", "Vienna"], ans: "New York" },
  { q: "OPEC ka main objective?", options: ["Oil production coordination", "Space research", "Nuclear disarmament", "Internet governance"], ans: "Oil production coordination" },
  { q: "IMF ka primary focus?", options: ["International monetary cooperation", "Military alliance", "Climate treaty enforcement", "Space missions"], ans: "International monetary cooperation" },
  { q: "World Trade Organization (WTO) ka HQ?", options: ["Geneva", "New York", "London", "Berlin"], ans: "Geneva" },
  { q: "SAARC me India ke alawa Nepal kis region ka group hai?", options: ["South Asia", "Europe", "Africa", "South America"], ans: "South Asia" },

  { q: "Largest gland in human body?", options: ["Liver", "Pancreas", "Thyroid", "Adrenal"], ans: "Liver" },
  { q: "Smallest bone in human body?", options: ["Stapes", "Femur", "Tibia", "Ulna"], ans: "Stapes" },
  { q: "Vitamin D ka deficiency kis disease se linked?", options: ["Rickets", "Scurvy", "Beriberi", "Pellagra"], ans: "Rickets" },
  { q: "Vitamin C deficiency se kya hota hai?", options: ["Scurvy", "Rickets", "Night blindness", "Beriberi"], ans: "Scurvy" },
  { q: "Insulin hormone kis organ se secret hota hai?", options: ["Pancreas", "Liver", "Kidney", "Thyroid"], ans: "Pancreas" },

  { q: "Earth ka largest ocean?", options: ["Pacific", "Atlantic", "Indian", "Arctic"], ans: "Pacific" },
  { q: "Earth ka longest river (common GK answer)?", options: ["Nile", "Ganga", "Amazon", "Yangtze"], ans: "Nile" },
  { q: "Atmosphere me sabse zyada gas?", options: ["Nitrogen", "Oxygen", "CO2", "Argon"], ans: "Nitrogen" },
  { q: "Longitude 0° ko kya kehte hain?", options: ["Prime Meridian", "Tropic of Cancer", "Equator", "International Date Line"], ans: "Prime Meridian" },
  { q: "World ka highest peak?", options: ["Mount Everest", "K2", "Kangchenjunga", "Makalu"], ans: "Mount Everest" },
{ q: "‘Doctrine of Lapse’ ka sambandh kis Governor-General se tha?", options: ["Lord Dalhousie", "Lord Curzon", "Lord Ripon", "Warren Hastings"], ans: "Lord Dalhousie" },
  { q: "‘Subsidiary Alliance’ policy ko kisne introduce kiya?", options: ["Lord Wellesley", "Lord Dalhousie", "Lord Canning", "Lord Cornwallis"], ans: "Lord Wellesley" },
  { q: "‘Permanent Settlement’ ko India me kisne implement kiya?", options: ["Lord Cornwallis", "Lord Wellesley", "Lord Ripon", "Lord Curzon"], ans: "Lord Cornwallis" },
  { q: "‘Ilbert Bill’ controversy kis Governor-General/Viceroy ke time me hui?", options: ["Lord Ripon", "Lord Curzon", "Lord Lytton", "Lord Canning"], ans: "Lord Ripon" },
  { q: "Indian National Congress ka first session kahan hua?", options: ["Bombay", "Calcutta", "Madras", "Allahabad"], ans: "Bombay" },

  { q: "Buddha ka first sermon (Dhammachakkappavattana) kahan diya gaya?", options: ["Sarnath", "Bodh Gaya", "Kushinagar", "Lumbini"], ans: "Sarnath" },
  { q: "Jainism me Tirthankara Parshvanath ka symbol kya mana jata hai?", options: ["Snake", "Lion", "Bull", "Lotus"], ans: "Snake" },
  { q: "Ashoka ke shasan me ‘Dhamma Mahamatra’ ka main role kya tha?", options: ["Dhamma ka prachar/prashasan", "Tax collection", "Army command", "Trade regulation"], ans: "Dhamma ka prachar/prashasan" },
  { q: "Harappan civilization ka port town kaunsa tha?", options: ["Lothal", "Kalibangan", "Dholavira", "Rakhigarhi"], ans: "Lothal" },
  { q: "Gupta period ko ‘Golden Age’ kehne ka ek major reason?", options: ["Art/Science/Literature growth", "Only military expansion", "Only sea trade", "Only urban decline"], ans: "Art/Science/Literature growth" },

  { q: "Indian Constitution ka ‘Basic Structure’ doctrine kis case se associated hai?", options: ["Kesavananda Bharati case", "Golaknath case", "Maneka Gandhi case", "ADM Jabalpur case"], ans: "Kesavananda Bharati case" },
  { q: "Fundamental Rights ko suspend karne ka provision mainly kis Article se linked hai?", options: ["Article 359", "Article 19", "Article 368", "Article 112"], ans: "Article 359" },
  { q: "‘Right to Property’ ab kis form me exist karta hai?", options: ["Legal right (Article 300A)", "Fundamental right (Article 32)", "DPSP (Article 40)", "Fundamental duty"], ans: "Legal right (Article 300A)" },
  { q: "Lok Sabha speaker ka casting vote kab use hota hai?", options: ["Tie (equal votes) me", "Budget pass karte waqt", "President election me", "Only money bill me"], ans: "Tie (equal votes) me" },
  { q: "Finance Commission ka constitutional base?", options: ["Article 280", "Article 356", "Article 110", "Article 324"], ans: "Article 280" },

  { q: "‘Quorum’ Lok Sabha me minimum presence kitna hota hai?", options: ["1/10 of total members", "1/2 of total members", "1/3 of total members", "2/3 of total members"], ans: "1/10 of total members" },
  { q: "Rajya Sabha ka presiding officer kaun hota hai?", options: ["Vice President of India", "President of India", "Prime Minister", "Chief Justice"], ans: "Vice President of India" },
  { q: "Parliamentary privileges primarily kahan defined hain?", options: ["Constitution + parliamentary law", "IPC", "CRPC", "Only conventions"], ans: "Constitution + parliamentary law" },
  { q: "Contingency Fund of India ka operator kaun hota hai?", options: ["President (executed by Govt)", "CAG", "Supreme Court", "Election Commission"], ans: "President (executed by Govt)" },
  { q: "CAG ko Indian Constitution me kis part ka guardian kaha jata hai?", options: ["Public finance/accountability", "Foreign policy", "Defence strategy", "Judicial appointments"], ans: "Public finance/accountability" },

  { q: "Inflation measure karne ke liye India me commonly kaunsa index use hota hai?", options: ["CPI", "HDI", "IIP", "GVA"], ans: "CPI" },
  { q: "Repo rate ka matlab?", options: ["RBI lends to banks", "Banks lend to RBI", "Govt lends to RBI", "Public lends to banks"], ans: "RBI lends to banks" },
  { q: "Reverse repo ka matlab?", options: ["Banks lend to RBI", "RBI lends to banks", "Govt borrows from banks", "Banks lend to public"], ans: "Banks lend to RBI" },
  { q: "GDP at factor cost se GDP at market price me conversion me kya add hota hai?", options: ["Indirect taxes - subsidies", "Direct taxes - subsidies", "Exports - imports", "Savings - investment"], ans: "Indirect taxes - subsidies" },
  { q: "Balance of Payments ka current account mainly kis cheez ko cover karta hai?", options: ["Trade in goods/services + transfers", "Only FDI", "Only forex reserves", "Only govt borrowing"], ans: "Trade in goods/services + transfers" },

  { q: "‘El Niño’ ka primary effect India me often kis par hota hai?", options: ["Monsoon variability", "Earthquake frequency", "Volcano eruptions", "Tidal waves"], ans: "Monsoon variability" },
  { q: "Coriolis force kis cheez ke karan hota hai?", options: ["Earth’s rotation", "Earth’s revolution", "Gravity variation", "Magnetic field"], ans: "Earth’s rotation" },
  { q: "Ozone layer atmosphere ke kis layer me hoti hai?", options: ["Stratosphere", "Troposphere", "Mesosphere", "Thermosphere"], ans: "Stratosphere" },
  { q: "Earth ka approx age?", options: ["4.54 billion years", "1.2 billion years", "10 billion years", "0.54 billion years"], ans: "4.54 billion years" },
  { q: "Igneous rocks ka formation kis process se hota hai?", options: ["Magma/lava cooling", "Sediment compaction", "Metamorphism only", "Organic deposition"], ans: "Magma/lava cooling" },

  { q: "Speed of light in vacuum approx?", options: ["3×10^8 m/s", "3×10^6 m/s", "1.5×10^8 m/s", "9.8 m/s²"], ans: "3×10^8 m/s" },
  { q: "SI unit of magnetic flux?", options: ["Weber", "Tesla", "Henry", "Farad"], ans: "Weber" },
  { q: "SI unit of magnetic field (flux density)?", options: ["Tesla", "Weber", "Ohm", "Coulomb"], ans: "Tesla" },
  { q: "Transformer ka working principle?", options: ["Mutual induction", "Electrolysis", "Photoelectric effect", "Thermionic emission"], ans: "Mutual induction" },
  { q: "Semiconductor me majority carriers ka example (n-type)?", options: ["Electrons", "Protons", "Neutrons", "Holes only"], ans: "Electrons" },

  { q: "RNA me nitrogenous base thymine ki jagah kya hota hai?", options: ["Uracil", "Cytosine", "Adenine", "Guanine"], ans: "Uracil" },
  { q: "Human chromosome number (diploid)?", options: ["46", "44", "48", "23"], ans: "46" },
  { q: "Codon kis molecule par present hota hai?", options: ["mRNA", "tRNA", "rRNA", "DNA polymerase"], ans: "mRNA" },
  { q: "Antibody mainly kaunsi cells banati hain?", options: ["Plasma cells", "RBC", "Neuron", "Platelets"], ans: "Plasma cells" },
  { q: "Kidney ka functional unit?", options: ["Nephron", "Neuron", "Alveoli", "Axon"], ans: "Nephron" },

  { q: "p-block elements periodic table me kaunse groups me aate hain?", options: ["13–18", "1–2", "3–12", "All groups"], ans: "13–18" },
  { q: "‘Aqua regia’ kis mixture ko kehte hain?", options: ["Conc. HCl + conc. HNO3", "H2SO4 + H2O", "NaOH + HCl", "H2O2 + H2O"], ans: "Conc. HCl + conc. HNO3" },
  { q: "Strong electrolyte ka example?", options: ["NaCl (aq)", "Glucose solution", "Urea solution", "Distilled water"], ans: "NaCl (aq)" },
  { q: "pH scale ka base kis ion concentration par hai?", options: ["H+ (hydrogen ion)", "OH- only", "Na+ only", "Cl- only"], ans: "H+ (hydrogen ion)" },
  { q: "Oxidation number O ka usually kya hota hai (most compounds)?", options: ["-2", "-1", "+2", "0"], ans: "-2" },

  { q: "‘Kyoto Protocol’ primarily kis cheez se related hai?", options: ["Greenhouse gas reduction", "Nuclear disarmament", "Ocean law", "World trade rules"], ans: "Greenhouse gas reduction" },
  { q: "‘Montreal Protocol’ ka focus?", options: ["Ozone-depleting substances", "Plastic ban", "Forest rights", "Wetland protection"], ans: "Ozone-depleting substances" },
  { q: "Biodiversity hotspot ka general meaning?", options: ["High endemism + high threat", "High rainfall only", "High altitude only", "High population only"], ans: "High endemism + high threat" },
  { q: "Acid rain ka major cause?", options: ["SO2 & NOx", "CO & CH4", "O2 & N2", "He & Ne"], ans: "SO2 & NOx" },
  { q: "Eutrophication mainly kis se hota hai?", options: ["Nitrates/phosphates enrichment", "Low salinity", "Earth rotation", "Deforestation only"], ans: "Nitrates/phosphates enrichment" },
   { q: "‘Bicameralism’ ka meaning kya hota hai?", options: ["Do-sadan wali legislature", "Single executive", "Single judiciary", "Federalism only"], ans: "Do-sadan wali legislature" },
  { q: "Indian Constitution me ‘Residuary powers’ kiske paas hote hain?", options: ["Union", "State", "Concurrent list", "Local bodies"], ans: "Union" },
  { q: "Article 72 President ko kis power se related hai?", options: ["Pardon power", "Emergency power", "Money bill assent", "Judicial review"], ans: "Pardon power" },
  { q: "Article 161 kaunse authority se related hai?", options: ["Governor’s pardon power", "PM appointment", "Finance Commission", "CAG audit"], ans: "Governor’s pardon power" },
  { q: "Zero Hour Indian Parliament me kya hota hai?", options: ["Question Hour ke baad matters raise", "Budget introduction time", "Midnight session", "Voting only"], ans: "Question Hour ke baad matters raise" },

  { q: "‘Question Hour’ generally kab hota hai?", options: ["Session ka first hour", "Lunch ke baad", "Session ke end me", "Only Friday"], ans: "Session ka first hour" },
  { q: "Anti-Defection law mainly kis schedule me hai?", options: ["Tenth Schedule", "First Schedule", "Fourth Schedule", "Twelfth Schedule"], ans: "Tenth Schedule" },
  { q: "Preamble me ‘Socialist’ aur ‘Secular’ shabd kis amendment se add hue?", options: ["42nd Amendment", "44th Amendment", "52nd Amendment", "61st Amendment"], ans: "42nd Amendment" },
  { q: "National Emergency ka article kaunsa hai?", options: ["Article 352", "Article 356", "Article 360", "Article 324"], ans: "Article 352" },
  { q: "State Emergency/President’s Rule ka article?", options: ["Article 356", "Article 352", "Article 368", "Article 370"], ans: "Article 356" },

  { q: "Financial Emergency ka article?", options: ["Article 360", "Article 356", "Article 352", "Article 110"], ans: "Article 360" },
  { q: "Fundamental Rights ka ‘heart and soul’ kisne kaha?", options: ["B. R. Ambedkar (Article 32)", "Gandhi (Article 19)", "Nehru (DPSP)", "Patel (Schedule 8)"], ans: "B. R. Ambedkar (Article 32)" },
  { q: "Directive Principles enforceable hote hain?", options: ["Nahi, non-justiciable", "Haan, directly enforceable", "Only Supreme Court enforce", "Only Parliament enforce"], ans: "Nahi, non-justiciable" },
  { q: "Concurrent List ka concept India ne kahan se liya?", options: ["Australia", "USA", "UK", "France"], ans: "Australia" },
  { q: "‘Judicial Review’ ka feature India ne mainly kahan se liya?", options: ["USA", "UK", "Canada", "Ireland"], ans: "USA" },

  { q: "GDP deflator ka use kis cheez ke liye hota hai?", options: ["Nominal to real GDP convert", "Population measure", "Trade deficit", "Tax slab"], ans: "Nominal to real GDP convert" },
  { q: "Stagflation ka meaning?", options: ["High inflation + low growth", "Low inflation + high growth", "Only deflation", "Only high growth"], ans: "High inflation + low growth" },
  { q: "Gresham’s law ka gist?", options: ["Bad money drives out good", "Supply creates demand", "Demand creates supply", "More tax more revenue always"], ans: "Bad money drives out good" },
  { q: "Repo rate badhne se generally kya hota hai?", options: ["Borrowing cost ↑", "Borrowing cost ↓", "Inflation guaranteed ↑", "Exports guaranteed ↑"], ans: "Borrowing cost ↑" },
  { q: "CRR ka matlab?", options: ["Banks ka RBI me mandatory reserve", "Govt ka gold reserve", "Foreign trade ratio", "Consumer price rule"], ans: "Banks ka RBI me mandatory reserve" },

  { q: "Acid rain me major acids kaunsi hoti hain?", options: ["H2SO4 & HNO3", "HCl & HF", "H2CO3 only", "CH3COOH only"], ans: "H2SO4 & HNO3" },
  { q: "Tectonic plates mostly kis layer par float karti hain?", options: ["Asthenosphere", "Inner core", "Outer core", "Mesosphere (atmosphere)"], ans: "Asthenosphere" },
  { q: "Earth ke core ka major composition (general)?", options: ["Iron & Nickel", "Silicon & Oxygen", "Aluminium & Copper", "Carbon & Hydrogen"], ans: "Iron & Nickel" },
  { q: "Tsunami ka most common cause?", options: ["Undersea earthquake", "Cyclone", "Thunderstorm", "Heat wave"], ans: "Undersea earthquake" },
  { q: "Jet streams kis layer me paye jate hain?", options: ["Upper troposphere", "Exosphere", "Ionosphere only", "Lower stratosphere only"], ans: "Upper troposphere" },

  { q: "Poiseuille’s law kis flow se related hai?", options: ["Viscous fluid flow in tube", "Ideal gas diffusion", "Light refraction", "Magnetism"], ans: "Viscous fluid flow in tube" },
  { q: "Bernoulli’s principle ka key idea?", options: ["Speed ↑, pressure ↓", "Speed ↑, pressure ↑", "Pressure independent of speed", "Only for solids"], ans: "Speed ↑, pressure ↓" },
  { q: "‘Escape velocity’ depend karti hai mainly kis par?", options: ["Planet mass & radius", "Planet temperature only", "Atmosphere only", "Magnetic field only"], ans: "Planet mass & radius" },
  { q: "Optics me ‘myopia’ correct kis lens se hota hai?", options: ["Concave lens", "Convex lens", "Cylindrical lens only", "No lens"], ans: "Concave lens" },
  { q: "Optics me ‘hypermetropia’ correct kis lens se hota hai?", options: ["Convex lens", "Concave lens", "Prism", "Plane glass"], ans: "Convex lens" },

  { q: "p–n junction forward bias me depletion region ka kya hota hai?", options: ["Decreases", "Increases", "No change", "Infinite ho jata hai"], ans: "Decreases" },
  { q: "Zener diode mainly kis use ke liye famous hai?", options: ["Voltage regulation", "Current amplification", "Light emission", "Oscillation"], ans: "Voltage regulation" },
  { q: "Logic gate AND ka output 1 kab hota hai?", options: ["Jab sab inputs 1 ho", "Kisi ek input 1 ho", "Jab sab inputs 0 ho", "Kabhi nahi"], ans: "Jab sab inputs 1 ho" },
  { q: "Logic gate OR ka output 0 kab hota hai?", options: ["Jab sab inputs 0 ho", "Jab sab inputs 1 ho", "Kisi ek input 1 ho", "Always 0"], ans: "Jab sab inputs 0 ho" },
  { q: "Boolean algebra me NOT gate ka output?", options: ["Input ka complement", "Input same", "Always 1", "Always 0"], ans: "Input ka complement" },

  { q: "PCR technique ka use kis cheez ke liye hota hai?", options: ["DNA amplification", "Protein folding", "Cell respiration", "Vaccine storage"], ans: "DNA amplification" },
  { q: "Enzyme ‘amylase’ kis par act karta hai?", options: ["Starch", "Fat", "Protein", "DNA"], ans: "Starch" },
  { q: "Bile juice ka main role?", options: ["Fat emulsification", "Protein digestion", "Starch digestion", "Oxygen transport"], ans: "Fat emulsification" },
  { q: "Human heart me chambers kitne hote hain?", options: ["4", "2", "3", "5"], ans: "4" },
  { q: "Lymph ka main function?", options: ["Fluid balance & immunity support", "O2 carry", "RBC production", "Bone formation"], ans: "Fluid balance & immunity support" },

  { q: "Periodic table me ‘lanthanides’ kis block se associated hain?", options: ["f-block", "s-block", "p-block", "d-block"], ans: "f-block" },
  { q: "Transition metals ka general feature?", options: ["Variable oxidation states", "Always +1 only", "Always non-metal", "Always colorless compounds"], ans: "Variable oxidation states" },
  { q: "Haber process ka final product?", options: ["Ammonia (NH3)", "Nitric acid (HNO3)", "Urea", "Methane"], ans: "Ammonia (NH3)" },
  { q: "Ozone ka molecular formula?", options: ["O3", "O2", "CO3", "N3"], ans: "O3" },
  { q: "Graphite electricity conduct kyun karta hai?", options: ["Delocalized electrons", "High density only", "Ionic bonding", "No free electrons"], ans: "Delocalized electrons" },

  { q: "‘Elution’ term commonly kis technique me aati hai?", options: ["Chromatography", "Distillation", "Sublimation", "Electroplating"], ans: "Chromatography" },
  { q: "SI unit of frequency?", options: ["Hertz", "Newton", "Joule", "Ampere"], ans: "Hertz" },
  { q: "Radioactivity me ‘half-life’ ka meaning?", options: ["Time for half nuclei to decay", "Time to double mass", "Time to change state", "Time to stop decay"], ans: "Time for half nuclei to decay" },
  { q: "Nuclear fission me generally kya hota hai?", options: ["Heavy nucleus splits", "Light nuclei combine", "Electrons split", "Protons vanish"], ans: "Heavy nucleus splits" },
  { q: "Nuclear fusion me generally kya hota hai?", options: ["Light nuclei combine", "Heavy nucleus splits", "Only gamma absorption", "No energy release"], ans: "Light nuclei combine" },

   { q: "Quit India Movement kis saal launch hua?", options: ["1942", "1940", "1930", "1947"], ans: "1942" },
  { q: "‘Do or Die’ slogan kis movement se linked hai?", options: ["Quit India Movement", "Non-Cooperation", "Civil Disobedience", "Swadeshi"], ans: "Quit India Movement" },
  { q: "Indian National Army (INA) ka slogan ‘Jai Hind’ popular kisne kiya?", options: ["Subhas Chandra Bose", "M. K. Gandhi", "Jawaharlal Nehru", "Sardar Patel"], ans: "Subhas Chandra Bose" },
  { q: "Simon Commission ka boycott kis reason se hua?", options: ["No Indian member", "High taxation", "Language issue", "Only princely states supported"], ans: "No Indian member" },
  { q: "Rowlatt Act kis year me pass hua?", options: ["1919", "1909", "1935", "1942"], ans: "1919" },

  { q: "Jallianwala Bagh massacre kis city me hua?", options: ["Amritsar", "Lahore", "Delhi", "Kanpur"], ans: "Amritsar" },
  { q: "Non-Cooperation Movement kis year start hua?", options: ["1920", "1915", "1930", "1942"], ans: "1920" },
  { q: "Civil Disobedience Movement ka formal start kis event se mana jata hai?", options: ["Dandi March", "Champaran Satyagraha", "Khilafat Movement", "Partition of Bengal"], ans: "Dandi March" },
  { q: "Dandi March kis year me hua?", options: ["1930", "1922", "1919", "1935"], ans: "1930" },
  { q: "Cripps Mission India kab aaya?", options: ["1942", "1939", "1946", "1920"], ans: "1942" },

  { q: "‘Cabinet Mission’ kis year me aaya?", options: ["1946", "1942", "1930", "1919"], ans: "1946" },
  { q: "Partition of Bengal (first) kis year me hua?", options: ["1905", "1911", "1892", "1920"], ans: "1905" },
  { q: "Bengal partition ko annul kis year kiya gaya?", options: ["1911", "1909", "1921", "1931"], ans: "1911" },
  { q: "‘Home Rule League’ (1916) ke key leaders me kaun the?", options: ["Tilak & Annie Besant", "Gandhi & Nehru", "Patel & Bose", "Roy & Tagore"], ans: "Tilak & Annie Besant" },
  { q: "‘Lucknow Pact’ kis year me hua?", options: ["1916", "1909", "1920", "1935"], ans: "1916" },

  { q: "Indian Constitution me ‘Schedules’ kitne hain (originally)?", options: ["8", "10", "12", "6"], ans: "8" },
  { q: "Fundamental Duties kis part me hain?", options: ["Part IVA", "Part III", "Part V", "Part IX"], ans: "Part IVA" },
  { q: "Panchayati Raj constitutional status kis amendment se mila?", options: ["73rd Amendment", "74th Amendment", "42nd Amendment", "44th Amendment"], ans: "73rd Amendment" },
  { q: "Urban local bodies ko constitutional status kis amendment se mila?", options: ["74th Amendment", "73rd Amendment", "61st Amendment", "52nd Amendment"], ans: "74th Amendment" },
  { q: "Election Commission of India ka article?", options: ["Article 324", "Article 280", "Article 148", "Article 356"], ans: "Article 324" },

  { q: "Tropic of Cancer India me kitne states se pass hota hai?", options: ["8", "6", "10", "12"], ans: "8" },
  { q: "Standard Meridian of India (IST) ka longitude?", options: ["82°30'E", "75°E", "90°E", "0°"], ans: "82°30'E" },
  { q: "Brahmaputra nadi ka source region?", options: ["Tibet (Angsi/Chemayungdung area)", "Nepal Himalaya", "Western Ghats", "Aravalli"], ans: "Tibet (Angsi/Chemayungdung area)" },
  { q: "Sunderbans delta mainly kaun si nadiyon se bana hai?", options: ["Ganga-Brahmaputra", "Narmada-Tapi", "Godavari-Krishna", "Mahanadi-Subarnarekha"], ans: "Ganga-Brahmaputra" },
  { q: "‘Western Disturbances’ India me mainly kis season me rain laate hain?", options: ["Winter", "Summer", "Autumn", "Spring only"], ans: "Winter" },

  { q: "CFCs ka major environmental impact?", options: ["Ozone depletion", "Acid rain only", "Soil salinity", "Earthquakes"], ans: "Ozone depletion" },
  { q: "BOD ka full form (water quality)?", options: ["Biochemical Oxygen Demand", "Biological Oxygen Density", "Bacterial Oxide Demand", "Bio Oxide Depth"], ans: "Biochemical Oxygen Demand" },
  { q: "COD ka full form?", options: ["Chemical Oxygen Demand", "Carbon Oxygen Demand", "Chemical Oxide Density", "Critical Oxygen Deficit"], ans: "Chemical Oxygen Demand" },
  { q: "Greenhouse gases me kaunsa major contributor mana jata hai?", options: ["CO2", "Neon", "Helium", "Argon"], ans: "CO2" },
  { q: "Ecosystem me energy flow ka general nature?", options: ["Unidirectional", "Cyclic", "Random only", "Bidirectional always"], ans: "Unidirectional" },

  { q: "SI unit of capacitance?", options: ["Farad", "Henry", "Tesla", "Weber"], ans: "Farad" },
  { q: "Capacitor me energy store kis form me hoti hai?", options: ["Electric field", "Magnetic field", "Kinetic energy", "Chemical bond"], ans: "Electric field" },
  { q: "AC generator ka principle?", options: ["Electromagnetic induction", "Electrolysis", "Thermal conduction", "Photoelectric emission"], ans: "Electromagnetic induction" },
  { q: "Photoelectric effect ka explanation kisne diya (theory)?", options: ["Einstein", "Newton", "Bohr", "Rutherford"], ans: "Einstein" },
  { q: "De Broglie hypothesis kis cheez se related hai?", options: ["Matter waves", "Nuclear fission", "Thermal expansion", "Fluid viscosity"], ans: "Matter waves" },

  { q: "Human eye me ‘blind spot’ kis reason se hota hai?", options: ["No rods/cones at optic nerve exit", "Too many cones", "Lens absent", "Cornea damaged"], ans: "No rods/cones at optic nerve exit" },
  { q: "Hemoglobin me metal ion kaunsa hota hai?", options: ["Iron (Fe)", "Copper (Cu)", "Zinc (Zn)", "Sodium (Na)"], ans: "Iron (Fe)" },
  { q: "AIDS ka causative agent?", options: ["HIV", "HBV", "Plasmodium", "Mycobacterium"], ans: "HIV" },
  { q: "Malaria ka causative organism?", options: ["Plasmodium", "Virus", "Bacteria", "Algae"], ans: "Plasmodium" },
  { q: "Vaccination ka basic principle?", options: ["Immune memory develop karna", "RBC increase karna", "Bone growth", "Digestion improve"], ans: "Immune memory develop karna" },

  { q: "Stainless steel me major alloying element (iron ke alawa) kaunsa hota hai?", options: ["Chromium", "Calcium", "Sodium", "Mercury"], ans: "Chromium" },
  { q: "‘pH’ term ka origin kis concept se hai?", options: ["Power/potential of hydrogen", "Pressure of hydrogen", "Phase of hydrogen", "Polarity of hydrogen"], ans: "Power/potential of hydrogen" },
  { q: "Alkali metals periodic table me kaunse group me hote hain?", options: ["Group 1", "Group 2", "Group 17", "Group 18"], ans: "Group 1" },
  { q: "Halogens ka group?", options: ["Group 17", "Group 16", "Group 18", "Group 1"], ans: "Group 17" },
  { q: "Noble gases ka group?", options: ["Group 18", "Group 17", "Group 1", "Group 2"], ans: "Group 18" },

  { q: "‘Elasticity of demand’ ka simplest meaning?", options: ["Price change se demand sensitivity", "Tax collection capacity", "Supply chain speed", "Only income level"], ans: "Price change se demand sensitivity" },
  { q: "Perfect competition me firms kya hoti hain?", options: ["Price taker", "Price maker", "Monopoly leader", "Cartel only"], ans: "Price taker" },
  { q: "Opportunity cost ka meaning?", options: ["Next best alternative foregone", "Total cost + profit", "Only fixed cost", "Only variable cost"], ans: "Next best alternative foregone" },
  { q: "Fiscal deficit generally kya represent karta hai?", options: ["Total expenditure - total receipts (excluding borrowings)", "Exports - imports", "Savings - investment", "Inflation - deflation"], ans: "Total expenditure - total receipts (excluding borrowings)" },
  { q: "Disinvestment ka basic meaning?", options: ["Govt stake sell in PSU", "New tax impose", "Currency devalue", "Import ban"], ans: "Govt stake sell in PSU" },

  { q: "Bhakra Nangal project kis nadi par hai?", options: ["Sutlej", "Ganga", "Narmada", "Godavari"], ans: "Sutlej" },
  { q: "Hirakud dam kis nadi par bana hai?", options: ["Mahanadi", "Krishna", "Cauvery", "Brahmaputra"], ans: "Mahanadi" },
  { q: "Sardar Sarovar dam kis nadi par hai?", options: ["Narmada", "Tapi", "Mahi", "Godavari"], ans: "Narmada" },
  { q: "Tehri dam kis nadi par hai?", options: ["Bhagirathi", "Yamuna", "Chambal", "Son"], ans: "Bhagirathi" },
  { q: "Srisailam project kis nadi par constructed hai?", options: ["Krishna", "Kaveri", "Godavari", "Mahanadi"], ans: "Krishna" },

  { q: "‘River of Sorrow’ (India GK me commonly) kis nadi ko kaha jata hai?", options: ["Damodar", "Kosi", "Brahmaputra", "Mahanadi"], ans: "Damodar" },
  { q: "Kosi nadi ko Bihar me kis naam se jana jata hai (common GK)?", options: ["Sorrow of Bihar", "Sorrow of Bengal", "Sorrow of Deccan", "Sorrow of Punjab"], ans: "Sorrow of Bihar" },
  { q: "Godavari nadi ka source location?", options: ["Trimbakeshwar (Nashik)", "Amarkantak", "Gangotri", "Mahabaleshwar"], ans: "Trimbakeshwar (Nashik)" },
  { q: "Narmada nadi ka source?", options: ["Amarkantak", "Trimbakeshwar", "Gangotri", "Brahmagiri"], ans: "Amarkantak" },
  { q: "Ganga nadi ka glacier source?", options: ["Gangotri (Gaumukh)", "Siachen", "Zemu", "Baltoro"], ans: "Gangotri (Gaumukh)" },

  { q: "Indian monsoon ko primary driver kya mana jata hai?", options: ["Land-sea heating contrast", "Earthquakes", "Tides", "Volcanoes"], ans: "Land-sea heating contrast" },
  { q: "Cauvery nadi ka source?", options: ["Talakaveri (Brahmagiri hills)", "Amarkantak", "Trimbak", "Rohtang"], ans: "Talakaveri (Brahmagiri hills)" },
  { q: "Mahanadi ka source?", options: ["Sihawa hills (Chhattisgarh)", "Amarkantak", "Mahabaleshwar", "Gangotri"], ans: "Sihawa hills (Chhattisgarh)" },
  { q: "Chambal nadi kis nadi ki tributary hai?", options: ["Yamuna", "Ganga", "Brahmaputra", "Godavari"], ans: "Yamuna" },
  { q: "Son nadi kis nadi me milti hai?", options: ["Ganga", "Yamuna", "Narmada", "Tapti"], ans: "Ganga" },

  { q: "India me ‘fiscal federalism’ ka major institutional mechanism?", options: ["Finance Commission", "NITI Aayog", "SEBI", "UPSC"], ans: "Finance Commission" },
  { q: "‘GVA’ ka full form?", options: ["Gross Value Added", "Gross Volume Added", "General Value Average", "Global Value Added"], ans: "Gross Value Added" },
  { q: "Monetary Policy Committee (MPC) ka main objective?", options: ["Inflation targeting", "Census conduct", "Budget pass", "Trade treaty"], ans: "Inflation targeting" },
  { q: "‘Open Market Operations’ (OMO) ka use kaun karta hai?", options: ["RBI", "Supreme Court", "Parliament", "NITI Aayog"], ans: "RBI" },
  { q: "‘Liquidity trap’ concept kis situation ko describe karta hai?", options: ["Low interest rates + ineffective monetary policy", "High tax + high growth", "High exports + low imports", "Only banking fraud"], ans: "Low interest rates + ineffective monetary policy" },

  { q: "‘Real GDP’ ka meaning?", options: ["Inflation-adjusted GDP", "Nominal GDP only", "Only service sector GDP", "GDP + population"], ans: "Inflation-adjusted GDP" },
  { q: "‘Nominal GDP’ ka meaning?", options: ["Current prices at GDP", "Constant prices GDP", "Per capita GDP", "PPP GDP only"], ans: "Current prices at GDP" },
  { q: "‘PPP’ in economics stands for?", options: ["Purchasing Power Parity", "Public Private Partnership", "Price Payment Policy", "Primary Poverty Program"], ans: "Purchasing Power Parity" },
  { q: "‘Customs duty’ generally kis par lagti hai?", options: ["Import/Export goods", "Salary income", "Land holding", "Only services"], ans: "Import/Export goods" },
  { q: "‘Excise duty’ traditionally kis par lagti thi (classic concept)?", options: ["Manufacture of goods", "Imports", "Exports", "Property transfer"], ans: "Manufacture of goods" },

  { q: "Newton’s law of gravitation me force proportional to?", options: ["m1*m2 / r^2", "m1+m2 / r", "m1-m2 / r^2", "m1*m2*r^2"], ans: "m1*m2 / r^2" },
  { q: "Escape velocity Earth ke liye approx?", options: ["11.2 km/s", "3 km/s", "7.9 km/s", "1.6 km/s"], ans: "11.2 km/s" },
  { q: "SI unit of energy?", options: ["Joule", "Newton", "Pascal", "Tesla"], ans: "Joule" },
  { q: "‘Watt’ kis cheez ki unit hai?", options: ["Power", "Energy", "Force", "Charge"], ans: "Power" },
  { q: "Specific heat capacity ki SI unit?", options: ["J/kg·K", "J/K", "N/m", "W/m"], ans: "J/kg·K" },

  { q: "Isothermal process me kaunsa constant rehta hai?", options: ["Temperature", "Pressure", "Volume", "Internal energy always"], ans: "Temperature" },
  { q: "Adiabatic process me kya hota hai (ideal case)?", options: ["No heat exchange", "Temperature constant", "Pressure constant", "Volume constant"], ans: "No heat exchange" },
  { q: "Sound waves ka nature?", options: ["Longitudinal", "Transverse", "Electromagnetic", "Stationary only"], ans: "Longitudinal" },
  { q: "Light waves ka nature?", options: ["Transverse electromagnetic", "Longitudinal mechanical", "Only longitudinal", "Only matter wave"], ans: "Transverse electromagnetic" },
  { q: "‘Doppler effect’ kis cheez me change batata hai?", options: ["Observed frequency due to relative motion", "Amplitude due to medium", "Wavelength due to prism", "Speed due to gravity"], ans: "Observed frequency due to relative motion" },

  { q: "Mendel ke experiments ka plant?", options: ["Pea (Pisum sativum)", "Wheat", "Rice", "Maize"], ans: "Pea (Pisum sativum)" },
  { q: "Genetics me ‘phenotype’ ka meaning?", options: ["Observable traits", "Gene sequence only", "Chromosome count", "Only mutation"], ans: "Observable traits" },
  { q: "Genetics me ‘genotype’ ka meaning?", options: ["Genetic makeup", "Only appearance", "Blood group only", "Only RNA"], ans: "Genetic makeup" },
  { q: "Human digestion me protein ka primary enzyme (stomach)?", options: ["Pepsin", "Amylase", "Lipase", "Trypsin"], ans: "Pepsin" },
  { q: "Trypsin enzyme kahan se secrete hota hai?", options: ["Pancreas", "Stomach", "Liver", "Salivary glands"], ans: "Pancreas" },

  { q: "Atom ka atomic number represent karta hai?", options: ["Protons count", "Neutrons count", "Protons+neutrons", "Electrons+neutrons"], ans: "Protons count" },
  { q: "Isotopes me kya same hota hai?", options: ["Atomic number", "Mass number", "Neutrons number", "Chemical formula always different"], ans: "Atomic number" },
  { q: "Isobars me kya same hota hai?", options: ["Mass number", "Atomic number", "Electrons number", "Valency always"], ans: "Mass number" },
  { q: "pH 7 solution ka nature?", options: ["Neutral", "Acidic", "Basic", "Strong acid"], ans: "Neutral" },
  { q: "Metal generally electrons lose karke kya banta hai?", options: ["Cation", "Anion", "Isotope", "Radical only"], ans: "Cation" },

  { q: "‘No-confidence motion’ kis house me move hota hai?", options: ["Lok Sabha", "Rajya Sabha", "Both houses", "State assembly only"], ans: "Lok Sabha" },
  { q: "‘Adjournment motion’ ka main purpose?", options: ["Urgent public matter discussion", "Budget pass", "President election", "Law commission setup"], ans: "Urgent public matter discussion" },
  { q: "Supreme Court ke judges retire kis age par hote hain?", options: ["65 years", "62 years", "60 years", "70 years"], ans: "65 years" },
  { q: "High Court judge retirement age?", options: ["62 years", "65 years", "60 years", "58 years"], ans: "62 years" },
  { q: "‘Writ jurisdiction’ mainly kis article se Supreme Court ko milti hai?", options: ["Article 32", "Article 356", "Article 368", "Article 75"], ans: "Article 32" },

  { q: "Indian Constitution me Supreme Court ka establishment kis Article me hai?", options: ["Article 124", "Article 32", "Article 148", "Article 280"], ans: "Article 124" },
  { q: "Money Bill ko define kaun sa article karta hai?", options: ["Article 110", "Article 112", "Article 114", "Article 116"], ans: "Article 110" },
  { q: "Impeachment of President ka provision kis Article me hai?", options: ["Article 61", "Article 72", "Article 356", "Article 368"], ans: "Article 61" },
  { q: "Attorney General of India ka article?", options: ["Article 76", "Article 74", "Article 148", "Article 280"], ans: "Article 76" },
  { q: "Comptroller and Auditor General (CAG) ka article?", options: ["Article 148", "Article 124", "Article 320", "Article 352"], ans: "Article 148" },

  { q: "UPSC ka constitutional article?", options: ["Article 315", "Article 280", "Article 324", "Article 165"], ans: "Article 315" },
  { q: "Election Commission ka article?", options: ["Article 324", "Article 356", "Article 280", "Article 75"], ans: "Article 324" },
  { q: "Finance Commission ka article?", options: ["Article 280", "Article 110", "Article 315", "Article 324"], ans: "Article 280" },
  { q: "GST Council ka constitutional base?", options: ["Article 279A", "Article 280", "Article 368", "Article 110"], ans: "Article 279A" },
  { q: "Parliament ko state list par (national interest) law banane ka power kis Article se?", options: ["Article 249", "Article 356", "Article 352", "Article 370"], ans: "Article 249" },

  { q: "Specific resistance (resistivity) temperature badhne par metal me generally?", options: ["Increase", "Decrease", "Same", "Zero ho jata hai"], ans: "Increase" },
  { q: "Superconductors me resistance kya hota hai (critical temp ke below)?", options: ["Zero", "Very high", "Constant", "Depends on length only"], ans: "Zero" },
  { q: "SI unit of electric charge?", options: ["Coulomb", "Ampere", "Volt", "Ohm"], ans: "Coulomb" },
  { q: "1 Volt ka definition (basic) kis se related hai?", options: ["Work per unit charge", "Charge per unit time", "Force per unit mass", "Power per unit area"], ans: "Work per unit charge" },
  { q: "Electric power ka formula?", options: ["P = VI", "P = IR", "P = V/R", "P = I/V"], ans: "P = VI" },

  { q: "Work-energy theorem kya kehta hai?", options: ["Net work = change in kinetic energy", "Net work = change in potential energy only", "Energy always increases", "Momentum always constant"], ans: "Net work = change in kinetic energy" },
  { q: "Momentum ka SI unit?", options: ["kg·m/s", "N·m", "kg·m/s²", "J/s"], ans: "kg·m/s" },
  { q: "Impulse ka relation momentum se?", options: ["Impulse = change in momentum", "Impulse = momentum/velocity", "Impulse = force/area", "Impulse = energy/time"], ans: "Impulse = change in momentum" },
  { q: "Viscosity ki SI unit?", options: ["Pa·s", "N·m", "J", "W"], ans: "Pa·s" },
  { q: "Surface tension ki SI unit?", options: ["N/m", "N·m", "Pa", "J/s"], ans: "N/m" },

  { q: "Acids aur bases ka Bronsted-Lowry concept kya kehta hai?", options: ["Acid proton donor, base proton acceptor", "Acid electron donor, base electron acceptor", "Acid always strong, base always weak", "Acid only HCl, base only NaOH"], ans: "Acid proton donor, base proton acceptor" },
  { q: "Arrhenius acid ka definition?", options: ["Water me H+ increase", "Water me OH- increase", "Salt banata hai", "Only sour taste"], ans: "Water me H+ increase" },
  { q: "Arrhenius base ka definition?", options: ["Water me OH- increase", "Water me H+ increase", "Only bitter taste", "Only ammonia"], ans: "Water me OH- increase" },
  { q: "Electronegativity generally period me left to right?", options: ["Increase", "Decrease", "Same", "Random"], ans: "Increase" },
  { q: "Atomic radius generally period me left to right?", options: ["Decrease", "Increase", "Same", "Becomes infinite"], ans: "Decrease" },

  { q: "Hemophilia inheritance pattern (standard GK)?", options: ["X-linked recessive", "Autosomal dominant", "Y-linked", "Mitochondrial only"], ans: "X-linked recessive" },
  { q: "Sickle cell anemia kis type ka disorder hai?", options: ["Genetic (mutation) disorder", "Vitamin deficiency only", "Bacterial infection", "Fungal disease"], ans: "Genetic (mutation) disorder" },
  { q: "Plant transpiration me maximum water loss kis part se hota hai?", options: ["Stomata", "Roots", "Xylem", "Phloem"], ans: "Stomata" },
  { q: "Xylem ka main function?", options: ["Water/mineral transport", "Food transport", "Gas exchange", "Reproduction"], ans: "Water/mineral transport" },
  { q: "Phloem ka main function?", options: ["Food (sugar) transport", "Water transport", "Support only", "Transpiration"], ans: "Food (sugar) transport" },

  { q: "Coral reefs ko sensitive ecosystem kyon mana jata hai?", options: ["Temperature/pH changes se jaldi impact", "High gravity impact", "Only desert me milte", "Only freshwater me bante"], ans: "Temperature/pH changes se jaldi impact" },
  { q: "Mangroves ka major benefit?", options: ["Coastal protection & nurseries", "Desert formation", "Glacier growth", "Only tourism"], ans: "Coastal protection & nurseries" },
  { q: "Biosphere reserve ka main purpose?", options: ["Conservation + sustainable use", "Only mining", "Only urban expansion", "Only agriculture"], ans: "Conservation + sustainable use" },
  { q: "‘Shifting cultivation’ ko Northeast India me commonly kya kehte hain?", options: ["Jhum", "Kharif", "Rabi", "Bhoodan"], ans: "Jhum" },
  { q: "‘Black soil’ (regur) majorly kis crop ke liye suitable?", options: ["Cotton", "Tea", "Jute", "Rubber"], ans: "Cotton" },

  { q: "Rabi crops India me generally kab sow kiye jate hain?", options: ["Winter (Oct-Nov)", "Summer (Apr-May)", "Monsoon start (Jun)", "Spring (Feb)"], ans: "Winter (Oct-Nov)" },
  { q: "Kharif crops generally kab sow kiye jate hain?", options: ["Monsoon (Jun-Jul)", "Winter (Dec)", "Autumn (Oct)", "Spring (Mar)"], ans: "Monsoon (Jun-Jul)" },
  { q: "India ki largest lagoon lake (common GK)?", options: ["Chilika Lake", "Wular Lake", "Dal Lake", "Loktak Lake"], ans: "Chilika Lake" },
  { q: "Loktak lake kis state me hai?", options: ["Manipur", "Assam", "Kerala", "Gujarat"], ans: "Manipur" },
  { q: "Wular Lake kis UT/state me hai?", options: ["Jammu & Kashmir", "Himachal Pradesh", "Uttarakhand", "Sikkim"], ans: "Jammu & Kashmir" },

  { q: "‘Price elasticity of demand’ ka formula (basic)?", options: ["% change in quantity / % change in price", "% change in price / % change in quantity", "Price/Income", "Income/Price"], ans: "% change in quantity / % change in price" },
  { q: "‘Consumer surplus’ simplest meaning?", options: ["Willingness to pay - price paid", "Price paid - production cost", "Tax paid - subsidy", "Income - savings"], ans: "Willingness to pay - price paid" },
  { q: "Monopoly market structure me firm generally kya hoti hai?", options: ["Price maker", "Price taker", "No control", "Only govt firm"], ans: "Price maker" },
  { q: "Oligopoly me firms ka count typically?", options: ["Few", "Very many", "Only one", "Zero"], ans: "Few" },
  { q: "‘Budget’ constitutionally kaun present karta hai (Union level)?", options: ["Finance Minister", "Chief Justice", "CAG", "ECI"], ans: "Finance Minister" },

{ q: "Ajanta Caves primarily kis cheez ke liye famous hain?", options: ["Buddhist paintings", "Mughal gardens", "Modern murals", "Rock-cut mosques"], ans: "Buddhist paintings" },
  { q: "Ellora Caves me kaunsi religions ke monuments milte hain?", options: ["Buddhist, Hindu, Jain", "Only Hindu", "Only Buddhist", "Only Jain"], ans: "Buddhist, Hindu, Jain" },
  { q: "Konark Sun Temple kis state me hai?", options: ["Odisha", "Gujarat", "Rajasthan", "Bihar"], ans: "Odisha" },
  { q: "Khajuraho temples kis state me hain?", options: ["Madhya Pradesh", "Uttar Pradesh", "Odisha", "Tamil Nadu"], ans: "Madhya Pradesh" },
  { q: "Sanchi Stupa kis religion se associated hai?", options: ["Buddhism", "Jainism", "Islam", "Sikhism"], ans: "Buddhism" },

  { q: "‘Natyashastra’ traditionally kis se associated mana jata hai?", options: ["Bharata Muni", "Kalidasa", "Valmiki", "Panini"], ans: "Bharata Muni" },
  { q: "‘Sattriya’ dance form ka origin kis state se?", options: ["Assam", "Odisha", "Kerala", "Punjab"], ans: "Assam" },
  { q: "‘Kathakali’ kis state ka classical dance hai?", options: ["Kerala", "Uttar Pradesh", "Assam", "Gujarat"], ans: "Kerala" },
  { q: "‘Bharatanatyam’ ka origin commonly kis state se linked hai?", options: ["Tamil Nadu", "Rajasthan", "Punjab", "Bihar"], ans: "Tamil Nadu" },
  { q: "‘Odissi’ dance form kis state se related hai?", options: ["Odisha", "Maharashtra", "West Bengal", "Haryana"], ans: "Odisha" },

  { q: "Madhubani (Mithila) painting ka origin kis state me mana jata hai?", options: ["Bihar", "Uttar Pradesh", "Rajasthan", "Kerala"], ans: "Bihar" },
  { q: "Pashmina shawl primarily kis region se associated hai?", options: ["Kashmir", "Kutch", "Malabar", "Bundelkhand"], ans: "Kashmir" },
  { q: "‘Warli’ painting tradition kis state se related hai?", options: ["Maharashtra", "Assam", "Punjab", "Odisha"], ans: "Maharashtra" },
  { q: "‘Pattachitra’ art form commonly kis state se linked hai?", options: ["Odisha", "Bihar", "Himachal Pradesh", "Haryana"], ans: "Odisha" },
  { q: "‘Blue pottery’ (Indian craft) commonly kis city se famous hai?", options: ["Jaipur", "Kolkata", "Pune", "Patna"], ans: "Jaipur" },

  { q: "Indian Constitution me ‘laws inconsistent with FR void’ ka article?", options: ["Article 13", "Article 12", "Article 14", "Article 19"], ans: "Article 13" },
  { q: "Equality before law ka article?", options: ["Article 14", "Article 15", "Article 16", "Article 17"], ans: "Article 14" },
  { q: "Abolition of Untouchability ka article?", options: ["Article 17", "Article 16", "Article 19", "Article 21"], ans: "Article 17" },
  { q: "Freedom of speech and expression kis article ka part hai?", options: ["Article 19", "Article 21", "Article 32", "Article 368"], ans: "Article 19" },
  { q: "Protection of life and personal liberty ka article?", options: ["Article 21", "Article 19", "Article 14", "Article 17"], ans: "Article 21" },

  { q: "Preventive detention safeguards (arrest/detention) ka core article?", options: ["Article 22", "Article 24", "Article 25", "Article 29"], ans: "Article 22" },
  { q: "Religious freedom (freedom of conscience) ka article?", options: ["Article 25", "Article 19", "Article 21", "Article 17"], ans: "Article 25" },
  { q: "Minorities’ educational institutions rights ka article?", options: ["Article 30", "Article 29", "Article 32", "Article 14"], ans: "Article 30" },
  { q: "Fundamental Duties ka article number?", options: ["Article 51A", "Article 50", "Article 49", "Article 52"], ans: "Article 51A" },
  { q: "DPSP me ‘international peace’ wala article?", options: ["Article 51", "Article 45", "Article 40", "Article 39A"], ans: "Article 51" },

  { q: "Bohr model me electron kaise move karta hai (postulate)?", options: ["Fixed energy orbits", "Random paths", "Inside nucleus", "Only straight line"], ans: "Fixed energy orbits" },
  { q: "SI unit of electric potential difference?", options: ["Volt", "Ampere", "Coulomb", "Ohm"], ans: "Volt" },
  { q: "Ohm (Ω) kis cheez ki unit hai?", options: ["Resistance", "Charge", "Power", "Frequency"], ans: "Resistance" },
  { q: "1 Ohm ka meaning (basic)?", options: ["1V causes 1A", "1A causes 1V", "1W causes 1J", "1C causes 1N"], ans: "1V causes 1A" },
  { q: "Series circuit me total resistance?", options: ["R = R1+R2+...", "R = 1/(1/R1+1/R2)", "R = R1-R2", "R = R1*R2"], ans: "R = R1+R2+..." },

  { q: "Parallel circuit me equivalent resistance relation?", options: ["1/R = 1/R1 + 1/R2 + ...", "R = R1+R2", "R = R1*R2", "R = R1-R2"], ans: "1/R = 1/R1 + 1/R2 + ..." },
  { q: "Lens power ki unit?", options: ["Diopter", "Tesla", "Weber", "Pascal"], ans: "Diopter" },
  { q: "Convex lens generally kaise behave karta hai?", options: ["Converging lens", "Diverging lens", "No refraction", "Only reflection"], ans: "Converging lens" },
  { q: "Concave lens generally kaise behave karta hai?", options: ["Diverging lens", "Converging lens", "No refraction", "Only reflection"], ans: "Diverging lens" },
  { q: "Human ear me balance kis part se maintain hota hai?", options: ["Semicircular canals", "Eardrum", "Cochlea", "Auditory nerve"], ans: "Semicircular canals" },

  { q: "ELISA test commonly kis cheez ke detection me use hota hai?", options: ["Antigen/antibody detection", "Blood pressure", "Bone density", "Vision power"], ans: "Antigen/antibody detection" },
  { q: "Plant cells me cell wall ka major component?", options: ["Cellulose", "Glycogen", "Chitin", "Keratin"], ans: "Cellulose" },
  { q: "Fungi cell wall ka major component?", options: ["Chitin", "Cellulose", "Peptidoglycan", "Keratin"], ans: "Chitin" },
  { q: "Bacteria cell wall ka major component?", options: ["Peptidoglycan", "Cellulose", "Chitin", "Starch"], ans: "Peptidoglycan" },
  { q: "Mitosis ka main result?", options: ["2 identical daughter cells", "4 different gametes", "Only DNA loss", "No division"], ans: "2 identical daughter cells" },

  { q: "Meiosis ka main result?", options: ["4 haploid cells", "2 diploid identical cells", "No genetic variation", "Only cytoplasm divide"], ans: "4 haploid cells" },
  { q: "Ribosome ka main function?", options: ["Protein synthesis", "ATP production", "Lipid digestion", "Photosynthesis"], ans: "Protein synthesis" },
  { q: "Enzyme ‘lipase’ kis par act karta hai?", options: ["Fats", "Proteins", "Starch", "DNA"], ans: "Fats" },
  { q: "Human body me ‘universal donor’ blood group?", options: ["O negative", "AB positive", "A positive", "B negative"], ans: "O negative" },
  { q: "Human body me ‘universal recipient’ blood group?", options: ["AB positive", "O negative", "A negative", "B positive"], ans: "AB positive" },

  { q: "Demand curve generally kaisi hoti hai?", options: ["Downward sloping", "Upward sloping", "Vertical always", "Horizontal always"], ans: "Downward sloping" },
  { q: "Law of demand ka core idea?", options: ["Price ↑ then demand ↓ (ceteris paribus)", "Price ↑ then demand ↑", "Demand independent of price", "Demand always constant"], ans: "Price ↑ then demand ↓ (ceteris paribus)" },
  { q: "Market equilibrium point kya show karta hai?", options: ["Demand = Supply", "Demand > Supply always", "Supply > Demand always", "Only inflation"], ans: "Demand = Supply" },
  { q: "Deflation ka meaning?", options: ["General price level fall", "General price level rise", "Money supply rise", "Tax rise"], ans: "General price level fall" },
  { q: "Inflation ka opposite term?", options: ["Deflation", "Stagflation", "Reflation", "Hyperinflation"], ans: "Deflation" },

  { q: "Kepler’s First Law kya kehta hai?", options: ["Planets move in elliptical orbits with Sun at one focus", "Planets move in perfect circles", "Planets have constant speed always", "Gravity is constant everywhere"], ans: "Planets move in elliptical orbits with Sun at one focus" },
  { q: "Kepler’s Second Law (law of areas) ka gist?", options: ["Equal areas in equal times", "Equal times in equal areas", "Orbit is circular", "Speed always constant"], ans: "Equal areas in equal times" },
  { q: "Kepler’s Third Law ka basic relation?", options: ["T^2 ∝ r^3", "T ∝ r^2", "T^3 ∝ r^2", "T ∝ 1/r"], ans: "T^2 ∝ r^3" },
  { q: "Light-year kya measure karta hai?", options: ["Distance", "Time", "Speed", "Brightness"], ans: "Distance" },
  { q: "Milky Way galaxy ka type (common classification)?", options: ["Spiral (barred spiral)", "Elliptical", "Irregular", "Ring only"], ans: "Spiral (barred spiral)" },

  { q: "Moon par ‘Sea of Tranquility’ kis mission se famous hua?", options: ["Apollo 11", "Apollo 13", "Viking 1", "Voyager 2"], ans: "Apollo 11" },
  { q: "Black hole se radiation escape na karne ka key reason?", options: ["Escape velocity > speed of light", "No gravity", "No mass", "Only magnetic field"], ans: "Escape velocity > speed of light" },
  { q: "Star ki energy ka primary source (main sequence) kya hota hai?", options: ["Nuclear fusion", "Nuclear fission", "Chemical burning", "Friction only"], ans: "Nuclear fusion" },
  { q: "H-R diagram me main sequence kya represent karta hai?", options: ["Stars ka temperature-luminosity relation band", "Only planets", "Only comets", "Only galaxies"], ans: "Stars ka temperature-luminosity relation band" },
  { q: "Red giant stage generally kis ke baad aata hai?", options: ["Main sequence", "White dwarf", "Neutron star", "Black hole"], ans: "Main sequence" },

  { q: "Ozone layer ka main role?", options: ["UV radiation absorb karna", "CO2 absorb karna", "Rain produce karna", "Winds stop karna"], ans: "UV radiation absorb karna" },
  { q: "Biomagnification ka meaning?", options: ["Trophic levels me toxin concentration increase", "Soil fertility increase", "Oxygen level increase", "Rainfall increase"], ans: "Trophic levels me toxin concentration increase" },
  { q: "Bioaccumulation ka meaning?", options: ["Organism me toxin accumulation over time", "Population sudden increase", "Forest cover increase", "Photosynthesis increase"], ans: "Organism me toxin accumulation over time" },
  { q: "Eutrophication ka main trigger?", options: ["Nutrients (N,P) excess", "Low gravity", "High altitude", "Magnetic storm"], ans: "Nutrients (N,P) excess" },
  { q: "Acid rain ka major precursor gases?", options: ["SO2 and NOx", "CH4 and CO", "O2 and N2", "He and Ne"], ans: "SO2 and NOx" },

  { q: "Montreal Protocol ka main objective?", options: ["Ozone-depleting substances control", "CO2 tax impose", "Ocean mining", "Nuclear test ban"], ans: "Ozone-depleting substances control" },
  { q: "Kyoto Protocol ka main focus?", options: ["Greenhouse gas emission reduction", "Wildlife census", "River linking", "Desert farming"], ans: "Greenhouse gas emission reduction" },
  { q: "Biodiversity hotspot ka core idea?", options: ["High endemism + high threat", "Only high rainfall", "Only large area", "Only deserts"], ans: "High endemism + high threat" },
  { q: "Endemic species ka meaning?", options: ["Restricted to particular region", "Found everywhere", "Migratory always", "Only aquatic"], ans: "Restricted to particular region" },
  { q: "In-situ conservation ka example?", options: ["National Park/Wildlife Sanctuary", "Zoo", "Seed bank", "Botanical garden only"], ans: "National Park/Wildlife Sanctuary" },

  { q: "Ex-situ conservation ka example?", options: ["Zoo", "Biosphere reserve", "National park", "Sacred groves"], ans: "Zoo" },
  { q: "Global warming ka direct driver kya hai?", options: ["Enhanced greenhouse effect", "Plate tectonics", "Earthquakes", "Tides"], ans: "Enhanced greenhouse effect" },
  { q: "Carbon footprint ka simplest meaning?", options: ["Total GHG emissions of an activity/person", "Only oxygen used", "Only water used", "Only plastic used"], ans: "Total GHG emissions of an activity/person" },
  { q: "Solid waste hierarchy me top priority kya hoti hai?", options: ["Reduce", "Recycle", "Landfill", "Incinerate"], ans: "Reduce" },
  { q: "Composting kis waste type ke liye best?", options: ["Biodegradable organic waste", "Metals", "Glass", "E-waste"], ans: "Biodegradable organic waste" },

  { q: "Swadeshi Movement ka major trigger (1905) kya tha?", options: ["Partition of Bengal", "Jallianwala Bagh", "Dandi March", "Rowlatt Act"], ans: "Partition of Bengal" },
  { q: "Ghadar Movement ka major base (early phase) kahan tha?", options: ["North America (USA/Canada)", "South Africa", "Japan", "Russia"], ans: "North America (USA/Canada)" },
  { q: "Khilafat Movement ka time period broadly?", options: ["1919–1924", "1905–1908", "1930–1932", "1942–1945"], ans: "1919–1924" },
  { q: "Chauri Chaura incident kis year me hua?", options: ["1922", "1919", "1930", "1942"], ans: "1922" },
  { q: "Gandhi ne Non-Cooperation Movement kis incident ke baad withdraw kiya?", options: ["Chauri Chaura", "Jallianwala Bagh", "Poona Pact", "Cripps Mission"], ans: "Chauri Chaura" },

  { q: "Poona Pact kis year me hua?", options: ["1932", "1920", "1916", "1942"], ans: "1932" },
  { q: "Poona Pact kin do leaders ke beech agreement se associated hai?", options: ["Gandhi & B. R. Ambedkar", "Nehru & Bose", "Patel & Tilak", "Tagore & Roy"], ans: "Gandhi & B. R. Ambedkar" },
  { q: "‘August Offer’ kis Viceroy ke time aaya?", options: ["Lord Linlithgow", "Lord Mountbatten", "Lord Curzon", "Lord Ripon"], ans: "Lord Linlithgow" },
  { q: "Wavell Plan kis year propose hua?", options: ["1945", "1935", "1942", "1919"], ans: "1945" },
  { q: "Mountbatten Plan kis year announce hua?", options: ["1947", "1946", "1942", "1930"], ans: "1947" },

  { q: "Thermodynamics ka First Law kis cheez ka statement hai?", options: ["Energy conservation", "Entropy always decreases", "Force conservation", "Charge creation"], ans: "Energy conservation" },
  { q: "Second Law of Thermodynamics ka gist?", options: ["Entropy of isolated system tends to increase", "Energy created", "Temperature always constant", "Pressure always increases"], ans: "Entropy of isolated system tends to increase" },
  { q: "Ideal gas equation?", options: ["PV = nRT", "P = VRT", "PV = RT", "P = nR/T"], ans: "PV = nRT" },
  { q: "Catalyst ka role chemical reaction me?", options: ["Rate change without being consumed", "Always increases mass", "Always shifts equilibrium permanently", "Stops reaction"], ans: "Rate change without being consumed" },
  { q: "Enthalpy (H) ka common unit?", options: ["Joule", "Tesla", "Weber", "Coulomb"], ans: "Joule" },

  { q: "DNA replication me enzyme jo new strand synthesize karta hai?", options: ["DNA polymerase", "RNA polymerase", "Ligase only", "Helicase only"], ans: "DNA polymerase" },
  { q: "DNA replication me helicase ka role?", options: ["Unwinds DNA", "Joins fragments", "Adds nucleotides", "Repairs proteins"], ans: "Unwinds DNA" },
  { q: "Cellular respiration me final electron acceptor (aerobic) kaun hota hai?", options: ["Oxygen", "Carbon dioxide", "Nitrogen", "Glucose"], ans: "Oxygen" },
  { q: "Photosynthesis ka main pigment?", options: ["Chlorophyll", "Hemoglobin", "Melanin", "Keratin"], ans: "Chlorophyll" },
  { q: "Ecology me ‘producer’ ka example?", options: ["Green plants", "Lion", "Fungi", "Eagle"], ans: "Green plants" },

  { q: "Food chain me ‘primary consumer’ example?", options: ["Herbivore", "Carnivore", "Decomposer", "Producer"], ans: "Herbivore" },
  { q: "Decomposers ka major example?", options: ["Bacteria/Fungi", "Birds", "Fish", "Algae"], ans: "Bacteria/Fungi" },
  { q: "Gene expression me ‘transcription’ ka meaning?", options: ["DNA to RNA", "RNA to protein", "Protein to RNA", "DNA to protein directly"], ans: "DNA to RNA" },
  { q: "Gene expression me ‘translation’ ka meaning?", options: ["mRNA to protein", "DNA to RNA", "DNA repair", "Cell division"], ans: "mRNA to protein" },
  { q: "Ribosome ka location (eukaryotic) commonly?", options: ["Cytoplasm / rough ER", "Only nucleus", "Only mitochondria", "Only chloroplast"], ans: "Cytoplasm / rough ER" },

  { q: "CPU ka full form?", options: ["Central Processing Unit", "Computer Processing Unit", "Central Program Utility", "Control Processing Unit"], ans: "Central Processing Unit" },
  { q: "ALU ka full form?", options: ["Arithmetic Logic Unit", "Advanced Logic यूनिट", "Array Level Unit", "Application Logic Utility"], ans: "Arithmetic Logic Unit" },
  { q: "RAM generally kis type ki memory hoti hai?", options: ["Volatile", "Non-volatile", "Permanent", "Optical"], ans: "Volatile" },
  { q: "ROM generally kis type ki memory hoti hai?", options: ["Non-volatile", "Volatile", "Temporary cache", "Virtual"], ans: "Non-volatile" },
  { q: "Cache memory ka main role?", options: ["CPU access speed improve", "Long-term storage", "Power backup", "Network routing"], ans: "CPU access speed improve" },

  { q: "1 Byte me kitne bits hote hain?", options: ["8", "4", "16", "32"], ans: "8" },
  { q: "Binary number system me digits kaunse hote hain?", options: ["0 and 1", "0–9", "A–F", "1–8"], ans: "0 and 1" },
  { q: "Hexadecimal number system me base kya hota hai?", options: ["16", "10", "8", "2"], ans: "16" },
  { q: "Operating System ka primary function?", options: ["Resource management", "Only printing", "Only browsing", "Only coding"], ans: "Resource management" },
  { q: "Process scheduling ka concept mainly kis layer se related hai?", options: ["Operating System", "Monitor", "Keyboard driver only", "CPU hardware only"], ans: "Operating System" },

  { q: "TCP/IP model me reliable delivery mainly kis protocol se?", options: ["TCP", "UDP", "ICMP", "ARP"], ans: "TCP" },
  { q: "UDP ka key feature?", options: ["Connectionless", "Always reliable", "Guaranteed ordering", "Encryption by default"], ans: "Connectionless" },
  { q: "DNS ka primary role?", options: ["Domain name to IP resolve", "Encrypt traffic", "Store files", "Run OS"], ans: "Domain name to IP resolve" },
  { q: "HTTP ka default port (classic)?", options: ["80", "21", "25", "53"], ans: "80" },
  { q: "HTTPS ka default port?", options: ["443", "80", "22", "110"], ans: "443" },

  { q: "SMTP protocol mainly kis kaam aata hai?", options: ["Email sending", "Email receiving", "File transfer", "Remote login"], ans: "Email sending" },
  { q: "IMAP/POP3 generally kis liye use hote hain?", options: ["Email receiving", "Web hosting", "DNS resolution", "VPN tunneling"], ans: "Email receiving" },
  { q: "Database me ‘Primary key’ ka role?", options: ["Unique identification", "Duplicate allow", "Only formatting", "Only encryption"], ans: "Unique identification" },
  { q: "SQL ka full form?", options: ["Structured Query Language", "Standard Question Language", "System Query Logic", "Simple Query List"], ans: "Structured Query Language" },
  { q: "‘Normalization’ in DB ka goal?", options: ["Redundancy reduce & integrity improve", "Speed always maximize", "Only UI improve", "Data delete"], ans: "Redundancy reduce & integrity improve" },

  { q: "Firewall ka main purpose?", options: ["Network traffic filtering", "Increase RAM", "Monitor brightness", "Hard disk formatting"], ans: "Network traffic filtering" },
  { q: "Encryption ka core objective?", options: ["Confidentiality", "Only speed", "Only compression", "Only backup"], ans: "Confidentiality" },
  { q: "2-factor authentication (2FA) ka best description?", options: ["Two independent proofs of identity", "Two passwords same time", "Only OTP", "Only biometric"], ans: "Two independent proofs of identity" },
  { q: "Phishing attack me attacker kya try karta hai?", options: ["Credentials trick se lena", "RAM upgrade", "Virus removal", "Website optimize"], ans: "Credentials trick se lena" },
  { q: "Malware ka broad meaning?", options: ["Malicious software", "Licensed software", "Open-source only", "Hardware fault"], ans: "Malicious software" },

  { q: "Money ka basic function kaunsa nahi hai?", options: ["Weather forecasting", "Medium of exchange", "Store of value", "Unit of account"], ans: "Weather forecasting" },
  { q: "Inflation generally kis cheez ko reduce karti hai?", options: ["Purchasing power", "Exports always", "Production always", "Employment always"], ans: "Purchasing power" },
  { q: "Repo rate increase ka likely effect?", options: ["Loans expensive", "Loans cheaper", "Money supply definitely increases", "Gold becomes currency"], ans: "Loans expensive" },
  { q: "Bank me ‘Demand deposit’ ka example?", options: ["Savings/Current account", "Fixed deposit only", "PPF only", "Bonds only"], ans: "Savings/Current account" },
  { q: "‘Time deposit’ ka example?", options: ["Fixed deposit (FD)", "Current account", "Cash in hand", "Wallet balance"], ans: "Fixed deposit (FD)" },

  { q: "Cheque ka basic nature?", options: ["Bill of exchange drawn on banker", "Currency note", "Bond certificate", "Insurance policy"], ans: "Bill of exchange drawn on banker" },
  { q: "NEFT ka full form?", options: ["National Electronic Funds Transfer", "National Easy Finance Transfer", "Net Enabled Funds Transfer", "National E-Fund Tracking"], ans: "National Electronic Funds Transfer" },
  { q: "RTGS ka full form?", options: ["Real Time Gross Settlement", "Real Transfer Global System", "Rate Time Gross System", "Real Time Gateway Service"], ans: "Real Time Gross Settlement" },
  { q: "IFSC code ka purpose?", options: ["Bank branch identify (electronic transfer)", "ATM pin reset", "Tax calculation", "Loan interest set"], ans: "Bank branch identify (electronic transfer)" },
  { q: "UPI ka basic idea?", options: ["Instant bank-to-bank payment system", "Only credit card", "Only cash withdrawal", "Only international remittance"], ans: "Instant bank-to-bank payment system" },

  { q: "Reasoning: ‘All A are B’ aur ‘All B are C’ => correct conclusion?", options: ["All A are C", "All C are A", "No relation A-C", "Some A are not C"], ans: "All A are C" },
  { q: "Reasoning: ‘Some A are B’ aur ‘All B are C’ => correct conclusion?", options: ["Some A are C", "All A are C", "No A are C", "All C are A"], ans: "Some A are C" },
  { q: "Series: 2, 6, 12, 20, 30, ? (pattern n(n+1))", options: ["42", "40", "44", "36"], ans: "42" },
  { q: "Odd one out: CPU, RAM, Keyboard, ALU", options: ["Keyboard", "CPU", "RAM", "ALU"], ans: "Keyboard" },
  { q: "If 1 = 3, 2 = 3, 3 = 5, 4 = 4 then 5 = ?", options: ["4", "5", "3", "6"], ans: "4" },

  { q: "Logic: A is older than B; B is older than C. Who is youngest?", options: ["C", "A", "B", "Cannot say"], ans: "C" },
  { q: "Direction: North ke opposite direction kya hota hai?", options: ["South", "East", "West", "North-East"], ans: "South" },
  { q: "Coding: If CAT = DBU (each letter +1), then DOG = ?", options: ["EPH", "EOG", "DPI", "FQI"], ans: "EPH" },
  { q: "Analogy: CPU : Brain :: Computer memory : ?", options: ["Mind storage", "Keyboard", "Monitor", "Mouse"], ans: "Mind storage" },
  { q: "Syllogism: All fruits are sweet. Tomato is a fruit. Conclusion?", options: ["Tomato is sweet", "Tomato is not sweet", "No conclusion", "Tomato is bitter"], ans: "Tomato is sweet" },

  { q: "SI unit of data rate?", options: ["bps", "Byte", "Joule", "Tesla"], ans: "bps" },
  { q: "LAN ka full form?", options: ["Local Area Network", "Large Area Network", "Long Access Network", "Local Access Number"], ans: "Local Area Network" },
  { q: "WAN ka full form?", options: ["Wide Area Network", "World Access Network", "Wireless Area Network", "Web Area Node"], ans: "Wide Area Network" },
  { q: "MAC address generally kitne bits ka hota hai (classic)?", options: ["48", "32", "64", "128"], ans: "48" },
  { q: "IPv4 address size?", options: ["32-bit", "128-bit", "64-bit", "16-bit"], ans: "32-bit" },

  { q: "IPv6 address size?", options: ["128-bit", "32-bit", "64-bit", "16-bit"], ans: "128-bit" },
  { q: "‘Open source’ software ka meaning?", options: ["Source code publicly available", "Always paid", "No updates", "Only offline"], ans: "Source code publicly available" },
  { q: "Compiler ka role?", options: ["High-level to machine code translate", "Hardware cooling", "Virus detect", "RAM expand"], ans: "High-level to machine code translate" },
  { q: "Interpreter ka role?", options: ["Line-by-line translate/execute", "Only compile once", "Only encrypt", "Only format disk"], ans: "Line-by-line translate/execute" },
  { q: "GUI ka full form?", options: ["Graphical User Interface", "General User Internet", "Graphics Utility Index", "Global UI Integration"], ans: "Graphical User Interface" },

  { q: "Article 20 Indian Constitution me kis cheez se related hai?", options: ["Protection in respect of conviction for offences", "Freedom of religion", "Right to education", "Election Commission"], ans: "Protection in respect of conviction for offences" },
  { q: "Article 21A kis right ko guarantee karta hai?", options: ["Right to Education", "Right to Property", "Right to Trade", "Right to Privacy only"], ans: "Right to Education" },
  { q: "DPSP me Uniform Civil Code kis article me hai?", options: ["Article 44", "Article 40", "Article 48", "Article 51A"], ans: "Article 44" },
  { q: "‘Official Language’ se related (Hindi) article?", options: ["Article 343", "Article 324", "Article 280", "Article 52"], ans: "Article 343" },
  { q: "Parliament ka power to amend Constitution kis Article me?", options: ["Article 368", "Article 352", "Article 356", "Article 110"], ans: "Article 368" },

  { q: "Right to Constitutional Remedies ka article?", options: ["Article 32", "Article 19", "Article 21", "Article 14"], ans: "Article 32" },
  { q: "‘Abolition of titles’ ka article?", options: ["Article 18", "Article 17", "Article 16", "Article 15"], ans: "Article 18" },
  { q: "Indian Constitution me ‘Council of Ministers’ se related article?", options: ["Article 74", "Article 124", "Article 148", "Article 324"], ans: "Article 74" },
  { q: "Prime Minister ka appointment President kis article ke under karta hai?", options: ["Article 75", "Article 76", "Article 72", "Article 61"], ans: "Article 75" },
  { q: "‘Comptroller and Auditor General’ ko remove kis process se kiya ja sakta hai?", options: ["Same as SC judge removal", "PM decision only", "Governor order", "Public referendum"], ans: "Same as SC judge removal" },

  { q: "Periodic table me सबसे अधिक electronegative element?", options: ["Fluorine", "Oxygen", "Chlorine", "Nitrogen"], ans: "Fluorine" },
  { q: "Noble gas me chemical reactivity low kyun hoti hai?", options: ["Stable valence shell", "High density", "High melting point", "Only because colorless"], ans: "Stable valence shell" },
  { q: "Electrolysis me cathode par kya hota hai?", options: ["Reduction", "Oxidation", "Neutralization", "Sublimation"], ans: "Reduction" },
  { q: "Electrolysis me anode par kya hota hai?", options: ["Oxidation", "Reduction", "Condensation", "Fusion"], ans: "Oxidation" },
  { q: "Galvanic (voltaic) cell me electricity ka source?", options: ["Spontaneous redox reaction", "External battery", "Heat only", "Pressure only"], ans: "Spontaneous redox reaction" },

  { q: "Human body me bile produce kaun karta hai?", options: ["Liver", "Pancreas", "Stomach", "Small intestine"], ans: "Liver" },
  { q: "Bile store kahan hoti hai?", options: ["Gall bladder", "Kidney", "Spleen", "Appendix"], ans: "Gall bladder" },
  { q: "Human respiratory system me gas exchange kahan hota hai?", options: ["Alveoli", "Trachea", "Larynx", "Bronchus only"], ans: "Alveoli" },
  { q: "RBC ka average lifespan approx?", options: ["120 days", "30 days", "365 days", "600 days"], ans: "120 days" },
  { q: "Platelets ka primary function?", options: ["Blood clotting", "Oxygen transport", "Antibody production", "Nerve impulse"], ans: "Blood clotting" },

  { q: "Sound intensity level commonly kis unit me measure hota hai?", options: ["Decibel (dB)", "Watt", "Joule", "Tesla"], ans: "Decibel (dB)" },
  { q: "Electric current I ka basic relation charge se?", options: ["I = Q/t", "I = V/R", "I = P/V", "I = R/V"], ans: "I = Q/t" },
  { q: "Capacitance ka relation charge & voltage se?", options: ["C = Q/V", "C = V/Q", "C = Q*V", "C = Q-V"], ans: "C = Q/V" },
  { q: "Magnetic field lines ka nature?", options: ["Closed loops", "Start at north and end at south only", "Never form loops", "Always straight"], ans: "Closed loops" },
  { q: "Earth ka magnetic north actually kis type ka hota hai (physics sense)?", options: ["Magnetic south pole", "Magnetic north pole", "Neutral point", "No pole"], ans: "Magnetic south pole" },

  { q: "India me IST time difference GMT/UTC se kitna hai?", options: ["+5:30", "+6:00", "+4:30", "+5:00"], ans: "+5:30" },
  { q: "International Date Line roughly kis longitude ke paas?", options: ["180°", "0°", "82°30'E", "90°E"], ans: "180°" },
  { q: "Earth ka largest continent?", options: ["Asia", "Africa", "North America", "Europe"], ans: "Asia" },
  { q: "World ka deepest ocean trench?", options: ["Mariana Trench", "Peru-Chile Trench", "Japan Trench", "Sunda Trench"], ans: "Mariana Trench" },
  { q: "Amazon river primarily kis ocean me milti hai?", options: ["Atlantic Ocean", "Pacific Ocean", "Indian Ocean", "Arctic Ocean"], ans: "Atlantic Ocean" },

  { q: "GDP per capita ka simplest meaning?", options: ["GDP / population", "Population / GDP", "Exports / imports", "Tax / GDP"], ans: "GDP / population" },
  { q: "‘Current account deficit’ ka simple meaning?", options: ["Imports + outflows > exports + inflows (current)", "Govt spending > tax", "Inflation > 10%", "FDI > FPI"], ans: "Imports + outflows > exports + inflows (current)" },
  { q: "‘Supply shock’ ka example?", options: ["Oil price sudden jump", "Tax cut", "Festival demand", "Salary increase"], ans: "Oil price sudden jump" },
  { q: "‘Moral hazard’ in banking generally kya hota hai?", options: ["Risky behavior due to protection", "Always honesty", "Only inflation", "Only taxation"], ans: "Risky behavior due to protection" },
  { q: "‘Adverse selection’ generally kis problem ko refer karta hai?", options: ["Hidden information leads to bad choices", "Too much transparency", "No market competition", "Only high profit"], ans: "Hidden information leads to bad choices" },

  { q: "Computer me ‘Kernel’ ka role?", options: ["Core OS component managing resources", "Only GUI theme", "Only antivirus", "Only web browser"], ans: "Core OS component managing resources" },
  { q: "IPv4 me total possible addresses approx?", options: ["4.3 billion", "128 billion", "1 million", "16 million"], ans: "4.3 billion" },
  { q: "URL ka full form?", options: ["Uniform Resource Locator", "Universal Resource Link", "Unique Routing Locator", "Unified Resource List"], ans: "Uniform Resource Locator" },
  { q: "ASCII ka full form?", options: ["American Standard Code for Information Interchange", "Advanced System Code for Internet Interface", "American Simple Code Information Index", "Automated Standard Code for Integrated Internet"], ans: "American Standard Code for Information Interchange" },
  { q: "Machine language me instructions generally kis form me hoti hain?", options: ["Binary", "English", "Hex words only", "Images"], ans: "Binary" },

  { q: "Reasoning: If all pens are books and all books are tables, then all pens are?", options: ["Tables", "Chairs", "No relation", "Not tables"], ans: "Tables" },
  { q: "Series: 1, 4, 9, 16, 25, ? ", options: ["36", "35", "49", "30"], ans: "36" },
  { q: "Odd one out: Mercury, Venus, Earth, Pluto", options: ["Pluto", "Mercury", "Venus", "Earth"], ans: "Pluto" },
  { q: "Analogy: Photosynthesis : Chlorophyll :: Respiration : ?", options: ["Mitochondria", "Chloroplast", "Ribosome", "Nucleus"], ans: "Mitochondria" },
  { q: "Syllogism: All mammals are animals. All dogs are mammals. Conclusion?", options: ["All dogs are animals", "All animals are dogs", "No dog is animal", "Some dogs are not animals"], ans: "All dogs are animals" },
];
